[package]
name = "vmm"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2018"

[dependencies]
kvm-bindings = { git = "https://github.com/firecracker-microvm/kvm-bindings", tag = "v0.3.0-2", features = ["fam-wrappers"] }
kvm-ioctls = { git = "https://github.com/firecracker-microvm/kvm-ioctls", tag = "v0.6.0-2" }
lazy_static = "1.4.0"
libc = ">=0.2.39"
serde = { version = ">=1.0.27", features = ["derive"] }
serde_json = ">=1.0.9"
sysconf = ">=0.3.4"
versionize = ">=0.1.2"
versionize_derive = ">=0.1.1"
vm-memory = { path = "../vm-memory" }
arch = { path = "../arch" }
devices = { path = "../devices" }
kernel = { path = "../kernel" }
logger = { path = "../logger" }
mmds = { path = "../mmds" }
polly = { path = "../polly" }
rate_limiter = { path = "../rate_limiter" }
seccomp = { path = "../seccomp" }
snapshot = { path = "../snapshot"}
utils = { path = "../utils" }

cpuid = { path = "../cpuid" }
